service: scrap-notify

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: provided
  region: eu-central-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: '*'

functions:
  scrap-notify:
    handler: bootstrap
    package:
      individually: true
      exclude:
        - '**/**'
      include:
        - ./bootstrap
    events:
        - schedule: cron(0/20 * * * ? *) #0 9 * * ? *